@startuml BitmapItem

class BitmapItem {

  - bufferedImage : BufferedImage
  - imageName : String

  # {static} FILE : String = "Arquivo"
  # {static} NOTFOUND : String = "não encontrado"

}

@enduml
