@startuml SlideViewerComponent

class SlideViewerComponent{

  - {static} serialVersionUID : long = 227L

  - {static} BGCOLOR : Color = Color.white
  - {static} COLOR : Color = Color.black
  - {static} FONTNAME : String = "Dialog"
  - {static} FONTSTYLE : int = Font.BOLD
  - {static} FONTHEIGHT : int = 10
  - {static} XPOS : int = 1100
  - {static} YPOS : int = 20

  - slide : Slide
  - labelFont : Font = null
  - presentation : Presentation = null
  - frame : JFrame = nul

  + SlideViewerComponent(pres : Presentation, frame : JFrame)
  + getPreferredSize() : Dimension
  + update(presentation : Presentation, data : Slide) : void
  + paintComponent(g : Graphics) : void

}

@enduml
