@startuml SlideViewerFrame

class SlideViewerFrame {

  - {static} serialVersionUID : long = 3227L

  - {static} JABTITLE : String = "Jabberpoint 1.6"

  + {static} WIDTH : int
  + {static} HEIGHT : int

  + SlideViewerFrame(title : String, presentation Presentation)
  + setupWindow(slideViewerComponent : SlideViewerComponent, presentation : Presentation)
  

}

@enduml
