@startuml Style

class Style {

  - {static} styles : Style[]

  - {static} FONTNAME : String = "Helvetica"
  + indent : int
  + color : Color
  + font : Font
  + fontSize : int
  + leadgin : int

  + {static} getStyle(level : int) : Style
  + Style(indent : int, color : Color, points : int, leading : int)
  + toString() : String
  + getFont(scale : float) : Font

}

@enduml
