@startuml Style

class Style {

  - {static} styles : Style[]

  - {static} FONTNAME : String = "Helvetica"
  + indent : int
  + color : Color
  + font : Font
  + fontSize : int
  + leadgin : int

}

@enduml
