@startuml XMLAccessor

class XMLAccessor {

  # {static} DEFAULT_API_TO_USE : String = "dom"

  # {static} SHOWTITLE : String = "showtitle"
  # {static} SLIDETITLE : String = "slidetitle"
  # {static} SLIDE : String = "slide"
  # {static} ITEM : String = "item"
  # {static} LEVEL : String = "level"
  # {static} KIND : String = "kind"
  # {static} TEXT : String = "text"
  # {static} IMAGE : String = "image"

  # {static} PCE : String = "Parser Configuration Exception"
  # {static} UNKNOWNTYPE : String = "Unknown Element type"
  # {static} NFE : String = "Number Format Exception"

  - getTitle(element : Element, tagName : String) : String
  + loadFile(presentation Presentation, filename : String) : void
  # loadSlideItem(slide : Slide, item : Element) : void
  + saveFile(presentation : Presentation, filename : String) : void


}

@enduml
