@startuml

left to right direction
arquivo as (Arquivo)
novoSlide as (Novo)
abrirSlide as (Abrir)
salvarSlide as (Salvar)
abrirAjuda as (Ajuda)
abrirSobre as (Sobre)
visualizar as (Visualizar)
proximoSlide as (Próximo)
slideAnterior as (Anteior)
pularPara as (Pular Para)

:Usuario: --> arquivo
:Usuario: --> abrirAjuda
:Usuario: --> visualizar
abrirAjuda <.. abrirSobre : <<extends>>
arquivo <.. novoSlide : <<extends>>
arquivo <.. abrirSlide : <<extends>>
arquivo <.. salvarSlide : <<extends>>
visualizar <.. proximoSlide : <<extends>>
visualizar <.. slideAnterior : <<extends>>
visualizar <.. pularPara : <<extends>>

@enduml
