@startuml abrirArquivo


Activate Interface
Activate MenuController
Interface -> MenuController : actionPerformed(ActionEvent actionEvent)

Activate XMLAccessor
MenuController -> XMLAccessor : loadFile(Presentation presentation, String fileName)
Deactivate MenuController

XMLAccessor --> Interface : repaint()
Deactivate XMLAccessor
Deactivate Interface

@enduml
