@startuml


Activate Interface

Activate MenuController
Interface -> MenuController : actionPerformed(ActionEvent actionEvent)

Activate AboutBox
MenuController -> AboutBox : show(Frame parent)
Deactivate MenuController

AboutBox -> Interface : repaint()

@enduml
